### ISSUE TITLE
CTF 관련 Entity, Repository를 생성한다.

### ISSUE THREAD

**Issue by shkisme** [KEEPER31337/Homepage-Back-R2#10]
## 📝 Description

CTF 관련 Entity, Repository를 생성합니다.

## ☑️ TODO

- [x] CtfChallenge Entity, Repository를 생성한다.
- [x] CtfChallengeCategory Entity, Repository를 생성한다.
- [x] CtfChallengeHasCtfChallengeCategory Entity, Repository를 생성한다.
- [x] CtfChallengeType Entity, Repository를 생성한다.
- [x] CtfContest Entity, Repository를 생성한다.
- [x] CtfDynamicChallengeInfo Entity, Repository를 생성한다.
- [x] CtfFlag Entity, Repository를 생성한다.
- [x] CtfSubmitLog Entity, Repository를 생성한다.
- [x] CtfTeam Entity, Repository를 생성한다.
- [x] CtfTeamHasMember Entity, Repository를 생성한다.

**Comment by shkisme** [comment]
CTF 페이지는 차순위로 두고 개발한다고 합니다.

**Comment by shkisme** [comment]
이젠 차순위가 아닌 CTF 😂
