### ISSUE TITLE
StaticWrite 관련 Entity, Repository를 생성한다.

### ISSUE THREAD

**Issue by shkisme** [KEEPER31337/Homepage-Back-R2#11]
## 📝 Description

StaticWrite 관련 Entity, Repository를 생성합니다.

## ☑️ TODO

- [x] StaticWriteContent Entity, Repository를 생성합니다.
- [x] StaticWriteSubtitleImage Entity, Repository를 생성합니다.
- [x] StaticWriteTitle Entity, Repository를 생성합니다.
