### ISSUE TITLE
Election 관련 Entity, Repository를 생성한다.

### ISSUE THREAD

**Issue by shkisme** [KEEPER31337/Homepage-Back-R2#12]
## 📝 Description

Election 관련 Entity, Repository를 생성합니다.

## ☑️ TODO

- [x] Election Entity, Repository를 생성한다.
- [x] ElectionCandidate Entity, Repository를 생성한다.
- [x] ElectionChartLog Entity, Repository를 생성한다.
- [x] ElectionVoter Entity, Repository를 생성한다.
