### ISSUE TITLE
Library(Book) 관련 Entity, Repository를 생성한다.

### ISSUE THREAD

**Issue by shkisme** [KEEPER31337/Homepage-Back-R2#15]
## 📝 Description

Library(Book) 관련 Entity, Repository를 생성한다.

## ☑️ TODO

- [x] Book Entity, Repository를 생성한다.
- [x] BookBorrowInfo Entity, Repository를 생성한다.
- [x] BookDepartment Entity, Repository를 생성한다.
