### ISSUE TITLE
baseball 야구 게임 백엔드 제작

### ISSUE THREAD

**Issue by gusah009** [KEEPER31337/Homepage-Back-R2#179]
## 📝 Description

야구게임 백엔드 제작

## ☑️ TODO

- [x] redisUtil object 저장할 수 있도록 변경
- [x] 오늘 게임 횟수 다 채웠는지 확인하는 API 추가
- [x] START 버튼 누를 때 시작 + 베팅 포인트 저장하는 API 추가
- [x] 타자 버튼 클릭 시 결과 알려주는 API 추가
    - response: 유저가 입력한 값, 결과, 몇 번째 시도인지

참고: 회차가 늘어날수록 받을 포인트는 감소해야 함.
