### ISSUE TITLE
Member 관련 Entity, Repository를 생성한다.

### ISSUE THREAD

**Issue by shkisme** [KEEPER31337/Homepage-Back-R2#3]
## 📝 Description

Member 관련 Entity, Repository를 생성합니다.

## ☑️ TODO

- [x] Member Entity, Repository를 생성한다.
- [x] MemberRank Entity, Repository를 생성한다.
- [x] MemberType Entity, Repository를 생성한다.
- [x] MemberJob Entity, Repository를 생성한다.
- [x] MemberHasMemberJob Entity, Repository를 생성한다.
- [ ] Friend Entity, Repository를 생성한다.
