### ISSUE TITLE
이메일, 로그인, 학번 중복 체크 기능을 구현한다.

### ISSUE THREAD

**Issue by shkisme** [KEEPER31337/Homepage-Back-R2#32]
## 📝 Description

이메일, 로그인, 학번 중복 체크 기능을 구현한다.

## ☑️ TODO

- [ ] 이메일 중복 체크 기능을 구현한다.
- [ ] 로그인 중복 체크 기능을 구현한다.
- [ ] 학번 중복 체크 기능을 구현한다.
