### ISSUE TITLE
Seminar 관련 Entity, Repository를 생성한다.

### ISSUE THREAD

**Issue by shkisme** [KEEPER31337/Homepage-Back-R2#4]
## 📝 Description

Seminar 관련 Entity, Repository를 생성합니다.
- `clerk` 폴더에 Survey와 함께 두면 됩니다.

## ☑️ TODO

- [ ] Seminar Entity, Repository를 생성한다.
- [ ] SeminarAttendance Entity, Repository를 생성한다.
- [ ] SeminarAttendanceStatus Entity, Repository를 생성한다.
- [ ] SeminarAttendanceExcuse Entity, Repository를 생성한다.
