### ISSUE TITLE
[FEAT] 야구 게임 배팅 금액, 획득 금액을 변경한다.

### ISSUE THREAD

**Issue by shkisme** [KEEPER31337/Homepage-Back-R2#430]
## 💬 기능 설명

야구게임을 할 수록 포인트 손해를 볼 수 있다는 의견이 있어서, 야구 게임 배팅 금액, 획득 금액을 변경합니다. 

https://github.com/KEEPER31337/Homepage-Back-R2/blob/b85c6297c1d855ba7427a46af6f959fcb4999ff0/src/main/java/com/keeper/homepage/domain/game/application/BaseballService.kt#L66-L68

위 코드에서 bettingPoint가 음수인지 뿐만 아니라, 1000 ~ 3000 사이인지 검사하는 코드를 추가합니다.

---

```kotlin
const val MAX_BETTING_POINT = 5000L
const val MIN_BETTING_POINT = 1000L
```
`MAX_BETTING_POINT` 상수를 3000L로 변경합니다.

---

https://github.com/KEEPER31337/Homepage-Back-R2/blob/b85c6297c1d855ba7427a46af6f959fcb4999ff0/src/main/java/com/keeper/homepage/domain/game/application/BaseballService.kt#L132-L135

earnablePoint를 추가하는 대신에, earnablePoint x 2를 추가합니다.

## ☑️ TODO

- [ ] bettingPoint가 1000 ~ 3000 사이인지 검사하는 코드 추가
- [ ] MAX_BETTING_POINT 상수를 3000L로 변경
- [ ] member 획득 포인트로 earnablePoint를 추가하는 대신에, earnablePoint x 2를 추가하도록 수정
