### ISSUE TITLE
Survey 관련 Entity, Repository를 생성한다.

### ISSUE THREAD

**Issue by shkisme** [KEEPER31337/Homepage-Back-R2#5]
## 📝 Description

Survey 관련 Entity, Repository를 생성합니다.
- survey 폴더를 만들어 작업하면 됩니다.

## ☑️ TODO

- [ ] Survey Entity, Repository를 생성한다.
- [ ] SurveyReply Entity, Repository를 생성한다.
- [ ] SurveyMemberReply Entity, Repository를 생성한다.
- [ ] SurveyReplyExcuse Entity, Repository를 생성한다.
