### ISSUE TITLE
Posting 관련 Entity, Repository를 생성한다.

### ISSUE THREAD

**Issue by shkisme** [KEEPER31337/Homepage-Back-R2#8]
## 📝 Description

Posting 관련 Entity, Repository를 생성합니다.

## ☑️ TODO

- [x] Posting Entity, Repository를 생성한다.
- [x] Comment Entity, Repository를 생성한다.
- [x] Category Entity, Repository를 생성한다.
- [ ] MemberHasPostingLike Entity, Repository를 생성한다.
- [ ] MemberHasPostingDislike Entity, Repository를 생성한다.
- [ ] MemberHasCommentLike Entity, Repository를 생성한다.
- [ ] #23

**Comment by geunskoo** [comment]
일차 목표 달성 !!
이번주 목요일까지
MemberHasPostingLike Entity, Repository
MemberHasPostingDislike Entity, Repository
MemberHasCommentLike Entity, Repository
완료하겠습니다~
